apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: zerodash-ingress

spec:
  rules:
    - http:
        paths:
          - backend:
              serviceName: zerodash-api-service
              servicePort: 80
            path: /