kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: event-reader
rules:
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "patch", "watch", "list", "create"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: event-reader
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
roleRef:
  kind: ClusterRole
  name: event-reader
  apiGroup: rbac.authorization.k8s.io